### ISSUE TITLE
issues with the "partial matching and regex"

### ISSUE THREAD

**Issue by henkisdabro** [mbaersch/url-cleaner#1]
Hi there and thanks for your excellent template! 

I tried using the checkbox which enables "partial match & regex" and can't really get that to work the way I thought it was intended. After enabling the checkbox, I've tried typing in:
`^action$`
`/^action$/`

as potentail formatting choices for regex, but both of those ideas seem to match very loosely (it does not take the `^$` assertions into account and/or I've typed the patterns incorrectly. Could you shed some light on how that box is intended? 

Is it possible to make two checkboxes instead - one which is simply a loose match and another more advanced box which supports full regex patterns, including a formatting guide?

**Comment by mbaersch** [comment]
Hi Henrik,

what exactly did you want to match with that pattern - can you give me an example URL and desired result? 

When active, the code uses a regular JavaScript match (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match) to determine if a parameter is to be white- or blacklisted. If not, a parameter must be equal to an entry on the list. 

using a blacklist on `https://www.domain.com/?foo=1&bar=0&action=PII+here&action2=keep` with "action" on the table results in 

`https://www.domain.com/?foo=1&bar=0`

if you use `^action$` instead, the result will only delete the first parameter and keeps `action2`

`https://www.test.com/?foo=1&bar=0&action2=keep`    

I just checked it and it works as expected / described above.

**Comment by henkisdabro** [comment]
Thanks for your reply and clarification on the formatting! Let me do some further testing as I did not see that behaviour. For me `action2` and `testaction` and `actions` were all removed regardless what I used in the box (tested various regex). Again, let me test again and get back to you, thanks!

**Comment by henkisdabro** [comment]
Here is an example I generated just now (using your recently updated template), which still produces the issue for me, let me know if you need more information to help?

URL in browser (GTM preview mode)
![2022-07-29 23_00_57-Home - Eat  Drink  HIlton](https://user-images.githubusercontent.com/477513/181788959-385a1688-894b-407a-abc6-f5ff327f16f9.png)

Page URL variable in GTM preview mode of the same site
![2022-07-29 23_01_19-Tag Assistant  Connected](https://user-images.githubusercontent.com/477513/181788962-b584304d-62ba-4942-bd74-bd798b16e90e.png)

URL Cleaner Variable output (which fails to blacklist the `actions` parameter
![2022-07-29 23_01_33-Tag Assistant  Connected](https://user-images.githubusercontent.com/477513/181788965-d475a380-792c-45dc-a2fd-0a6e872af059.png)

Screenshot of settings of the variable itself:
![2022-07-29 23_04_12-Google Tag Manager](https://user-images.githubusercontent.com/477513/181788969-c7a2c234-937b-4c9f-911e-67e799539e69.png)

**Comment by mbaersch** [comment]
This is easy: your parameter reads "action*s*" , not "action". A partial match would work but not what you configured here.

**Comment by mbaersch** [comment]
If you want to test without having to use an instance of the template and GTM preview you can open the template in the "Templates" section. The editor´s preview allows you to enter values and run the code. 

![image](https://user-images.githubusercontent.com/15323700/181792592-498015cb-4eec-4346-a3c4-1a46ae57c8bf.png)

**Comment by henkisdabro** [comment]
Oh gosh, I think I typed this up at too late an hour, you are of course correct! Thanks for entertaining the thought experiement nevertheless and also thanks for the excellent "Run Code" tip!

**Comment by mbaersch** [comment]
You are welcome 😉
