### ISSUE TITLE
caps not working in parameter list

### ISSUE THREAD

**Issue by herrNeuschulz** [mbaersch/url-cleaner#5]
In my url some parameters use caps, but they do not get cleaned up when I add them to the list how they are used in the URL. After I typed them in lower case it works, but probably not everyone will figure it out.

**Comment by mbaersch** [comment]
good catch! I planned to ignore case by lowercasing all parameter names in lists and then compare to lowercase parameter names but never touched list entries for several reasons. Fixed this, should be available via Gallery by tomorrow (hopefully)
